include make-compose.mk
include make-app.mk
include make-static.mk
include make-development.mk
include make-production.mk
include make-ansible.mk
include make-docker.mk
include make-gcloud.mk
include make-kube.mk
