name: On Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    if: github.repository == 'hexlet-basics/hexlet_basics'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run web tests
        run: |
          make web-ci-test
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Set Tag To The Env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Build Web
        run: make web-docker-build-production VERSION=$RELEASE_VERSION
      - name: Push Web
        run: make web-docker-push VERSION=$RELEASE_VERSION
      - name: Build Caddy
        run: make caddy-docker-build-production VERSION=$RELEASE_VERSION
      - name: Push Caddy
        run: make caddy-docker-push VERSION=$RELEASE_VERSION
      - uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: '#basics-code-auto'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
